ayy lmao

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -1,16 +1,62 @@
-#!/bin/sh
+#!/bin/bash
 #
 # dot
 #
 # `dot` handles installation, updates, things like that. Run it periodically
 # to make sure you're on the latest and greatest.
-export ZSH=$HOME/.dotfiles
 
-# Set OS X defaults
-$ZSH/osx/set-defaults.sh
+set -e
 
-# Upgrade homebrew
-brew update
+parentDirectory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
+dotfilesDirectory="$(cd "$(dirname "$parentDirectory")" && pwd -P)"
 
-# Install homebrew packages
-$ZSH/homebrew/install.sh 2>&1
+displayUsageAndExit() {
+    echo "dot -- dotfiles management"
+    echo ""
+    echo "Usage: dot [options]"
+    echo ""
+    echo "Options:"
+    echo "  -e, --edit    Open dotfiles directory for editing"
+    echo "  -h, --help    Show this help message and exit"
+    exit
+}
+
+while test $# -gt 0; do
+    case "$1" in
+    "-h" | "--help")
+        displayUsageAndExit
+        ;;
+    "-e" | "--edit")
+        exec "$EDITOR" "$dotfilesDirectory"
+        exit
+        ;;
+    *)
+        echo "Invalid option: $1"
+        displayUsageAndExit
+        ;;
+    esac
+    shift
+done
+
+if [[ $CODESPACES == "true" ]]; 
+then
+    export ZSH=/workspaces/.codespaces/.persistedshare/dotfiles
+else
+    export ZSH=$HOME/.dotfiles
+fi
+
+if [ "$(uname -s)" == "Darwin" ]; then
+    # Set macOS defaults
+    "$ZSH/macos/set-defaults.sh"
+
+    # Install homebrew
+    "$ZSH/homebrew/install.sh 2>&1"
+
+    # Upgrade homebrew
+    echo "› brew update"
+    brew update
+fi
+
+# Install software
+echo "› $ZSH/script/install"
+"$ZSH/script/install"
